#\source "https://rubygems.org"
#source "https://rubygems.org"
gem "rails", "~> 7.2.1"
gem "sprockets-rails"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem 'drb', '2.2.1'
gem "shoulda-matchers", "~> 5.3.0" # Solo una línea para shoulda-matchers
gem "rspec"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
group :development do
  gem "web-console"
end
group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem 'rspec-rails', '~> 4.0' # Solo una línea para rspec-rails
end

